In [229]:
import pandas as pd
import datetime
from datetime import datetime
import matplotlib
from matplotlib import pyplot as plt

In [179]:
d_parser = lambda x : pd.to_datetime.strftime(x, '%Y-%m-%d %I-%p',errors='coerce')
df = pd.read_csv('ETH_1h.csv', parse_dates=['Date'], date_format= d_parser)

In [165]:
df

                   Date  Symbol    Open    High     Low   Close      Volume
0      2020-03-13 08-PM  ETHUSD  129.94  131.82  126.87  128.71  1940673.93
1      2020-03-13 07-PM  ETHUSD  119.51  132.02  117.10  129.94  7579741.09
2      2020-03-13 06-PM  ETHUSD  124.47  124.85  115.50  119.51  4898735.81
3      2020-03-13 05-PM  ETHUSD  124.08  127.42  121.63  124.47  2753450.92
4      2020-03-13 04-PM  ETHUSD  124.85  129.51  120.17  124.08  4461424.71
...                 ...     ...     ...     ...     ...     ...         ...
23669  2017-07-01 03-PM  ETHUSD  265.74  272.74  265.00  272.57  1500282.55
23670  2017-07-01 02-PM  ETHUSD  268.79  269.90  265.00  265.74  1702536.85
23671  2017-07-01 01-PM  ETHUSD  274.83  274.93  265.00  268.79  3010787.99
23672  2017-07-01 12-PM  ETHUSD  275.01  275.01  271.00  274.83   824362.87
23673  2017-07-01 11-AM  ETHUSD  279.98  279.99  272.10  275.01   679358.87

[23674 rows x 7 columns]

In [181]:
df.head()

               Date  Symbol    Open    High     Low   Close      Volume
0  2020-03-13 08-PM  ETHUSD  129.94  131.82  126.87  128.71  1940673.93
1  2020-03-13 07-PM  ETHUSD  119.51  132.02  117.10  129.94  7579741.09
2  2020-03-13 06-PM  ETHUSD  124.47  124.85  115.50  119.51  4898735.81
3  2020-03-13 05-PM  ETHUSD  124.08  127.42  121.63  124.47  2753450.92
4  2020-03-13 04-PM  ETHUSD  124.85  129.51  120.17  124.08  4461424.71

In [187]:
df.loc[0,'Date'].day_name()

'Friday'

In [185]:
df['Date'] = pd.to_datetime(df['Date'], format = '%Y-%m-%d %I-%p')

In [189]:
df['Date'].dt.day_name()

0          Friday
1          Friday
2          Friday
3          Friday
4          Friday
           ...
23669    Saturday
23670    Saturday
23671    Saturday
23672    Saturday
23673    Saturday
Name: Date, Length: 23674, dtype: object

In [191]:
df['DayOfweek'] = df['Date'].dt.day_name()

In [193]:
df

,Date,Symbol,Open,High,Low,Close,Volume,DayOfweek
0,2020-03-13 20:00:00,ETHUSD,129.94,131.82,126.87,128.71,1940673.93,Friday
1,2020-03-13 19:00:00,ETHUSD,119.51,132.02,117.10,129.94,7579741.09,Friday
2,2020-03-13 18:00:00,ETHUSD,124.47,124.85,115.50,119.51,4898735.81,Friday
3,2020-03-13 17:00:00,ETHUSD,124.08,127.42,121.63,124.47,2753450.92,Friday
4,2020-03-13 16:00:00,ETHUSD,124.85,129.51,120.17,124.08,4461424.71,Friday
...,...,...,...,...,...,...,...,...
23669,2017-07-01 15:00:00,ETHUSD,265.74,272.74,265.00,272.57,1500282.55,Saturday
23670,2017-07-01 14:00:00,ETHUSD,268.79,269.90,265.00,265.74,1702536.85,Saturday
23671,2017-07-01 13:00:00,ETHUSD,274.83,274.93,265.00,268.79,3010787.99,Saturday
23672,2017-07-01 12:00:00,ETHUSD,275.01,275.01,271.00,274.83,824362.87,Saturday
23673,2017-07-01 11:00:00,ETHUSD,279.98,279.99,272.10,275.01,679358.87,Saturday

In [195]:
df['Date'].max()

Timestamp('2020-03-13 20:00:00')

In [197]:
df['Date'].min()

Timestamp('2017-07-01 11:00:00')

In [199]:
filta = (df['Date'] >= '2020')

In [201]:
df.loc[filta]

,Date,Symbol,Open,High,Low,Close,Volume,DayOfweek
0,2020-03-13 20:00:00,ETHUSD,129.94,131.82,126.87,128.71,1940673.93,Friday
1,2020-03-13 19:00:00,ETHUSD,119.51,132.02,117.10,129.94,7579741.09,Friday
2,2020-03-13 18:00:00,ETHUSD,124.47,124.85,115.50,119.51,4898735.81,Friday
3,2020-03-13 17:00:00,ETHUSD,124.08,127.42,121.63,124.47,2753450.92,Friday
4,2020-03-13 16:00:00,ETHUSD,124.85,129.51,120.17,124.08,4461424.71,Friday
...,...,...,...,...,...,...,...,...
1744,2020-01-01 04:00:00,ETHUSD,129.57,130.00,129.50,129.56,702786.82,Wednesday
1745,2020-01-01 03:00:00,ETHUSD,130.37,130.44,129.38,129.57,496704.23,Wednesday
1746,2020-01-01 02:00:00,ETHUSD,130.14,130.50,129.91,130.37,396315.72,Wednesday
1747,2020-01-01 01:00:00,ETHUSD,128.34,130.14,128.32,130.14,635419.40,Wednesday
1748,2020-01-01 00:00:00,ETHUSD,128.54,128.54,128.12,128.34,245119.91,Wednesday

In [203]:
df.set_index('Date', inplace = True)

In [205]:
df

,Symbol,Open,High,Low,Close,Volume,DayOfweek
Date,,,,,,,
2020-03-13 20:00:00,ETHUSD,129.94,131.82,126.87,128.71,1940673.93,Friday
2020-03-13 19:00:00,ETHUSD,119.51,132.02,117.10,129.94,7579741.09,Friday
2020-03-13 18:00:00,ETHUSD,124.47,124.85,115.50,119.51,4898735.81,Friday
2020-03-13 17:00:00,ETHUSD,124.08,127.42,121.63,124.47,2753450.92,Friday
2020-03-13 16:00:00,ETHUSD,124.85,129.51,120.17,124.08,4461424.71,Friday
...,...,...,...,...,...,...,...
2017-07-01 15:00:00,ETHUSD,265.74,272.74,265.00,272.57,1500282.55,Saturday
2017-07-01 14:00:00,ETHUSD,268.79,269.90,265.00,265.74,1702536.85,Saturday
2017-07-01 13:00:00,ETHUSD,274.83,274.93,265.00,268.79,3010787.99,Saturday
2017-07-01 12:00:00,ETHUSD,275.01,275.01,271.00,274.83,824362.87,Saturday
2017-07-01 11:00:00,ETHUSD,279.98,279.99,272.10,275.01,679358.87,Saturday

In [213]:
df.loc['2019']

,Symbol,Open,High,Low,Close,Volume,DayOfweek
Date,,,,,,,
2019-12-31 23:00:00,ETHUSD,128.33,128.69,128.14,128.54,440678.91,Tuesday
2019-12-31 22:00:00,ETHUSD,128.38,128.69,127.95,128.33,554646.02,Tuesday
2019-12-31 21:00:00,ETHUSD,127.86,128.43,127.72,128.38,350155.69,Tuesday
2019-12-31 20:00:00,ETHUSD,127.84,128.34,127.71,127.86,428183.38,Tuesday
2019-12-31 19:00:00,ETHUSD,128.69,128.69,127.60,127.84,1169847.84,Tuesday
...,...,...,...,...,...,...,...
2019-01-01 04:00:00,ETHUSD,130.75,133.96,130.74,131.96,2791135.37,Tuesday
2019-01-01 03:00:00,ETHUSD,130.06,130.79,130.06,130.75,503732.63,Tuesday
2019-01-01 02:00:00,ETHUSD,130.79,130.88,129.55,130.06,838183.43,Tuesday
2019-01-01 01:00:00,ETHUSD,131.62,131.62,130.77,130.79,434917.99,Tuesday
2019-01-01 00:00:00,ETHUSD,130.53,131.91,130.48,131.62,1067136.21,Tuesday

In [215]:
highs = df['High'].resample('D').max()

In [217]:
highs

Date
2017-07-01    279.99
2017-07-02    293.73
2017-07-03    285.00
2017-07-04    282.83
2017-07-05    274.97
               ...
2020-03-09    208.65
2020-03-10    206.28
2020-03-11    202.98
2020-03-12    195.64
2020-03-13    148.00
Freq: D, Name: High, Length: 987, dtype: float64

In [219]:
highs['2020-01-01']

132.68

In [233]:
%matplotlib inline

In [241]:
highs.plot()

In [245]:
df.resample('W').agg({'Close':'mean','High':'max','Volume':'sum',"Low":'min'})

                 Close    High        Volume     Low
Date
2017-07-02  268.202162  293.73  8.084631e+07  253.23
2017-07-09  261.062083  285.00  2.246746e+08  231.25
2017-07-16  195.698393  240.33  5.017750e+08  130.26
2017-07-23  212.783750  249.40  7.221637e+08  153.25
2017-07-30  203.309524  229.99  2.657305e+08  178.03
...                ...     ...           ...     ...
2020-02-16  255.198452  290.00  3.912867e+08  216.31
2020-02-23  265.321905  287.13  3.067838e+08  242.36
2020-03-01  236.373988  278.13  3.693920e+08  209.26
2020-03-08  229.817619  253.01  2.736569e+08  196.00
2020-03-15  176.332821  208.65  4.983998e+08   90.00

[142 rows x 4 columns]